### ISSUE TITLE
Link youtube thể hiện demo ứng dụng 

### ISSUE THREAD

**Issue by johngoodman2k** [johngoodman2k/Smart-Cooking-App#44]
link youtube thể hiện demo ứng dụng (có trình bày tiếng)

**Comment by khang1234dd** [comment]
https://github.com/johngoodman2k/Smart-Cooking-App/blob/main/SmartCookingApp_Project/Link_Demo.txt

Lin ytb: https://youtu.be/yAyVlWgpSrw (v.2.0)
