### ISSUE TITLE
File README

### ISSUE THREAD

**Issue by johngoodman2k** [johngoodman2k/Smart-Cooking-App#45]
file README.txt hướng dẫn cách thực thi code, yêu cầu thư viện cần cài đặt

**Comment by khang1234dd** [comment]
Xem hướng dẫn tại đây: https://github.com/johngoodman2k/Smart-Cooking-App/blob/main/README.md
Thư viện đã có sẵn trong project hoặc vào đây: https://github.com/johngoodman2k/Smart-Cooking-App/blob/main/SmartCookingApp_Project/README.md
