### ISSUE TITLE
 link youtube thể hiện demo ứng dụng (có trình bày tiếng)

### ISSUE THREAD

**Issue by johngoodman2k** [johngoodman2k/Smart-Cooking-App#58]
Phiên bản 3.0

**Comment by khang1234dd** [comment]
https://github.com/johngoodman2k/Smart-Cooking-App/blob/main/SmartCookingApp_Project/Link_Demo.txt (danh sách link version)
https://www.youtube.com/watch?v=5uZC8GdPXco (v3)
